#!/bin/bash
#Se compila el archivo y se ejecuta para luego comparar la salida con al salida esperada
archivo=$1
javac $archivo &> error
if [ $? -eq 0 ]; then			#checa que la compilacion haya jalado
	echo se ha compilado exitosamente
	ejecutable=${archivo%.*}	#toma el nombre del archivo sin el .java
	java $ejecutable &> salida
	cmp -s salida salida_esperada
	if [ $? -eq 0 ]; then		#archivos iguales = 0
		echo ACEPTADO
	else
		echo RECHAZAOOOO
	fi
else
	echo error de compilacion
fi
